****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPLZRMCA_INVOCING																																
0003																																
731																																
                40																																
%_HEADER																																
SAPLZRMCA_INVOCING                      0003 0003      6 82192 37  0  0 61 83  0G E                              20131009115021																																
%_DESCRIPTION																																
Maintain View: Detail Screen ZCO_IL_COSTCTR																																
%_FIELDS																																
ZCO_IL_COSTCTR-TELNO	2	CHAR	 15	30	00	00	30	00	  1	  2		  0	  0	  0		 15					  0	  0								Telephone No.	                                       00	
ZCO_IL_COSTCTR-TELNO	C	CHAR	 12	A0	00	80	30	00	  1	 18		  0	  0	  0		 12					 24	  0				KEY				____________	                                       00	
VIM_FRAME_FIELD		CHAR	 82	80	02	88	30	00	  3	  2		  0	  0	  0		  4	R				  0	  0	101							__________________________________________________________________________________		
ZCO_IL_COSTCTR-NAME	0	CHAR	120	30	00	00	30	00	  4	  3		  0	  0	  0		 60					  0	  0								+	                                       00	
ZCO_IL_COSTCTR-NAME	C	CHAR	120	A1	00	80	00	00	  4	 64		  0	  0	  0		 19					240	  0								________________________________________________________________________________________________________________________	                                       00	
ZCO_IL_COSTCTR-CO_CENTER	2	CHAR	 15	30	00	00	30	00	  5	  3		  0	  0	  0		 15			KOS		  0	  0								Cost Center	                                       00	
ZCO_IL_COSTCTR-CO_CENTER	C	CHAR	 10	A1	00	80	00	00	  5	 64		  0	  0	  0		 10			KOS	ALPHA	 20	  0								__________	                                       00	
OK_CODE		CHAR	  4	80	10	88	00	00	255	  4	O	  0	  0	  0		 20					  0	  0								____		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
 MODULE detail_init.																																
*																																
PROCESS AFTER INPUT.																																
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.																																
 MODULE DETAIL_SET_PFSTATUS.																																
 CHAIN.																																
    FIELD ZCO_IL_COSTCTR-TELNO .																																
    FIELD ZCO_IL_COSTCTR-NAME .																																
    FIELD ZCO_IL_COSTCTR-CO_CENTER .																																
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.																																
 endchain.																																
 chain.																																
    FIELD ZCO_IL_COSTCTR-TELNO .																																
  module detail_pai.																																
 endchain.																																
