****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPLZRMCA_INVOCING																																
0001																																
731																																
                40																																
%_HEADER																																
SAPLZRMCA_INVOCING                      0001 0001     61 69192 37  0  0 61 83  0G E                              20131009091555																																
%_DESCRIPTION																																
View maint: Overview screen ZGL_INT_LINES																																
%_FIELDS																																
TCTRL_ZGL_INT_LINES			 38	F8	FC	00	00	00	  1	  2	E	101	  1	  1		 59	T				  0	  0	101									
VIM_FRAME_FIELD		CHAR	 60	80	02	88	30	40	  1	  0	T	101	  1	  1		 60					  0	  0								____________________________________________________________		
*ZGL_INT_LINES-INVOICE_GL	2	CHAR	 40	30	00	00	30	A8	  1	  1	T	101	  1	  1		 15			SAK		  0	  0								G/L Account	X                                      00	
*ZGL_INT_LINES-CORRECTION_GL	2	CHAR	 40	30	00	00	30	88	  1	  2	T	101	  1	  1		 15			SAK		  0	  0								G/L Account	X                                      00	
VIM_MARKED		CHAR	  1	80	00	88	00	20	  1	  0	T	101	  1	  1		  1	C				  0	  0	103							_		
ZGL_INT_LINES-INVOICE_GL	C	CHAR	 10	B0	00	80	30	28	  1	  1	T	101	  1	  1		 15			SAK	ALPHA	 20	  0				KEY				__________	X                                      00	
ZGL_INT_LINES-CORRECTION_GL	C	CHAR	 10	B0	00	80	00	08	  1	  2	T	101	  1	  1		 15			SAK	ALPHA	 20	  0								__________	X                                      00	
VIM_POSI_PUSH		CHAR	 20	80	00	88	30	00	 61	 20		  0	  0	  0		 20	P				  0	  0	102							____________________	                                                                                                                                                                        POSI	
VIM_POSITION_INFO		CHAR	 30	80	02	88	33	00	 61	 41		  0	  0	  0		 30					  0	  0								______________________________		
OK_CODE		CHAR	  4	80	10	88	00	00	255	  4	O	  0	  0	  0		 20					  0	  0								____		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
 MODULE LISTE_INITIALISIEREN.																																
 LOOP AT EXTRACT WITH CONTROL																																
  TCTRL_ZGL_INT_LINES CURSOR NEXTLINE.																																
   MODULE LISTE_SHOW_LISTE.																																
 ENDLOOP.																																
*																																
PROCESS AFTER INPUT.																																
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.																																
 MODULE LISTE_BEFORE_LOOP.																																
 LOOP AT EXTRACT.																																
   MODULE LISTE_INIT_WORKAREA.																																
   CHAIN.																																
    FIELD ZGL_INT_LINES-INVOICE_GL .																																
    FIELD ZGL_INT_LINES-CORRECTION_GL .																																
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.																																
   ENDCHAIN.																																
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.																																
   CHAIN.																																
    FIELD ZGL_INT_LINES-INVOICE_GL .																																
    MODULE LISTE_UPDATE_LISTE.																																
   ENDCHAIN.																																
 ENDLOOP.																																
 MODULE LISTE_AFTER_LOOP.																																
