****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPLZASSETGRP																																
0003																																
700																																
                40																																
%_HEADER																																
SAPLZASSETGRP                           0003 0003     61 69192 37  0  0 61 83  0G E                              20151007134932																																
%_DESCRIPTION																																
View maint: Overview screen ZAS_USER																																
%_FIELDS																																
TCTRL_ZAS_USER			 19	F8	FC	00	00	00	  1	  2	E	101	  1	  1		 59	T				  0	  0	101									
VIM_FRAME_FIELD		CHAR	 60	80	02	88	30	40	  1	  0	T	101	  1	  1		 60					  0	  0								____________________________________________________________		
*ZAS_USER-USERNAME	3	CHAR	 40	20	00	00	30	A0	  1	  1	T	101	  1	  1		 12					  0	  0								User Name		
VIM_MARKED		CHAR	  1	80	00	88	00	20	  1	  0	T	101	  1	  1		  1	C				  0	  0	103							_		
ZAS_USER-USERNAME	C	CHAR	 12	B0	00	80	30	20	  1	  1	T	101	  1	  1		 12					 24	  0				KEY				____________	                                       00	
VIM_POSI_PUSH		CHAR	 20	80	00	88	30	00	 61	 20		  0	  0	  0		 20	P				  0	  0	102							____________________	                                                                                                                                                                        POSI	
VIM_POSITION_INFO		CHAR	 30	80	02	88	33	00	 61	 41		  0	  0	  0		 30					  0	  0								______________________________		
OK_CODE		CHAR	  4	80	10	88	00	00	255	  4	O	  0	  0	  0		 20					  0	  0								____		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
 MODULE LISTE_INITIALISIEREN.																																
 LOOP AT EXTRACT WITH CONTROL																																
  TCTRL_ZAS_USER CURSOR NEXTLINE.																																
   MODULE LISTE_SHOW_LISTE.																																
 ENDLOOP.																																
*																																
PROCESS AFTER INPUT.																																
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.																																
 MODULE LISTE_BEFORE_LOOP.																																
 LOOP AT EXTRACT.																																
   MODULE LISTE_INIT_WORKAREA.																																
   CHAIN.																																
    FIELD ZAS_USER-USERNAME .																																
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.																																
   ENDCHAIN.																																
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.																																
   CHAIN.																																
    FIELD ZAS_USER-USERNAME .																																
    MODULE LISTE_UPDATE_LISTE.																																
   ENDCHAIN.																																
 ENDLOOP.																																
 MODULE LISTE_AFTER_LOOP.																																
