****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPLZASSETGRP																																
0001																																
700																																
                40																																
%_HEADER																																
SAPLZASSETGRP                           0001 0001     61 83192 37  0  0 61 83  0G E                              20151215180935																																
%_DESCRIPTION																																
View maint: Overview screen ZAA_TRANSFER																																
%_FIELDS																																
TCTRL_ZAA_TRANSFER			 83	F8	FC	00	00	00	  1	  2	E	101	  1	  1		 59	T				  0	  0	101									
VIM_FRAME_FIELD		CHAR	 60	80	02	88	30	40	  1	  0	T	101	  1	  1		 60					  0	  0								____________________________________________________________		
*ZAA_TRANSFER-ZID	4	CHAR	 40	30	00	00	30	A0	  1	  1	T	101	  1	  1		 30					  0	  0								ID	X	
*ZAA_TRANSFER-SERNR	3	CHAR	 40	20	00	00	30	A0	  1	  2	T	101	  1	  1		 18			SER		  0	  0								Serial number		
*ZAA_TRANSFER-BUDAT	2	CHAR	 40	30	00	00	30	80	  1	  3	T	101	  1	  1		 15					  0	  0								Posting Date	X	
*ZAA_TRANSFER-SGTXT	3	CHAR	 40	20	00	00	30	80	  1	  4	T	101	  1	  1		 50					  0	  0								Text		
*ZAA_TRANSFER-SHOPSTORT	0	CHAR	 45	30	00	00	30	80	  1	  5	T	101	  1	  1		 45					  0	  0								Shop Location		
*ZAA_TRANSFER-STORT	2	CHAR	 40	30	00	00	30	80	  1	  6	T	101	  1	  1		 15					  0	  0								Location	X	
*ZAA_TRANSFER-ZST	4	CHAR	 40	30	00	00	30	80	  1	  7	T	101	  1	  1		  6					  0	  0								Status		
*ZAA_TRANSFER-ASSETCODE	3	CHAR	 40	20	00	00	30	80	  1	  8	T	101	  1	  1		 12			AN1		  0	  0								Asset		
*ZAA_TRANSFER-SUBNUMBER	4	CHAR	 40	30	00	00	30	80	  1	  9	T	101	  1	  1		  4			AN2		  0	  0								SNo.		
*ZAA_TRANSFER-NEWASSETCODE	3	CHAR	 40	20	00	00	30	80	  1	 10	T	101	  1	  1		 12			AN1		  0	  0								Asset		
*ZAA_TRANSFER-NEWSUBNUMBER	4	CHAR	 40	30	00	00	30	80	  1	 11	T	101	  1	  1		  4			AN2		  0	  0								SNo.		
*ZAA_TRANSFER-BUKRS	4	CHAR	 40	30	00	00	30	80	  1	 12	T	101	  1	  1		  4			BUK		  0	  0								CoCd	X	
*ZAA_TRANSFER-BELNR	2	CHAR	 40	30	00	00	30	80	  1	 13	T	101	  1	  1		 15			BLN		  0	  0								Document Number		
*ZAA_TRANSFER-GJAHR	4	CHAR	 40	30	00	00	30	80	  1	 14	T	101	  1	  1		  4			GJR		  0	  0								Year		
*ZAA_TRANSFER-USNAM	3	CHAR	 40	20	00	00	30	80	  1	 15	T	101	  1	  1		 12			USR		  0	  0								User Name		
*ZAA_TRANSFER-CPUDT	3	CHAR	 40	20	00	00	30	80	  1	 16	T	101	  1	  1		 10					  0	  0								Entry Date	X	
*ZAA_TRANSFER-MESSAGE		CHAR	 46	00	00	08	30	80	  1	 17	T	101	  1	  1		 46					  0	  0								Message		
VIM_MARKED		CHAR	  1	80	00	88	00	20	  1	  0	T	101	  1	  1		  1	C				  0	  0	102							_		
ZAA_TRANSFER-ZID	C	CHAR	  2	B0	00	81	30	28	  1	  1	T	101	  1	  1		 30					  4	  0				KEY				__	XDL                                    00	
ZAA_TRANSFER-SERNR	C	CHAR	 18	B0	00	80	30	20	  1	  2	T	101	  1	  1		 18			SER	GERNR	 36	  0				KEY				__________________	                                       00	
ZAA_TRANSFER-BUDAT	D	DATE	 10	B0	00	80	00	08	  1	  3	T	101	  1	  1		 15					 16	  0								__________	X                                      00	
ZAA_TRANSFER-SGTXT	C	CHAR	 50	B0	02	80	00	00	  1	  4	T	101	  1	  1		 50					100	  0								__________________________________________________	                                       00	
ZAA_TRANSFER-SHOPSTORT	C	CHAR	 10	A0	00	80	00	00	  1	  5	T	101	  1	  1		 10					 20	  0								__________	                                       00	
ZAA_TRANSFER-STORT	C	CHAR	 10	B0	00	84	00	08	  1	  6	T	101	  1	  1		 15					 20	  0								__________	X                                      00	
ZAA_TRANSFER-ZST	C	CHAR	  1	B0	00	80	00	00	  1	  7	T	101	  1	  1		  6					  2	  0								_	                                       00	
ZAA_TRANSFER-ASSETCODE	C	CHAR	 12	B0	00	80	00	00	  1	  8	T	101	  1	  1		 12			AN1	ALPHA	 24	  0								____________	                                       00	
ZAA_TRANSFER-SUBNUMBER	C	CHAR	  4	B0	00	80	00	00	  1	  9	T	101	  1	  1		  4			AN2	ALPHA	  8	  0								____	                                       00	
ZAA_TRANSFER-NEWASSETCODE	C	CHAR	 12	B0	00	80	00	00	  1	 10	T	101	  1	  1		 12			AN1	ALPHA	 24	  0								____________	                                       00	
ZAA_TRANSFER-NEWSUBNUMBER	C	CHAR	  4	B0	00	80	00	00	  1	 11	T	101	  1	  1		  4			AN2	ALPHA	  8	  0								____	                                       00	
ZAA_TRANSFER-BUKRS	C	CHAR	  4	B0	00	80	00	08	  1	 12	T	101	  1	  1		  4			BUK		  8	  0								____	X                                      00	
ZAA_TRANSFER-BELNR	C	CHAR	 12	B0	00	80	00	00	  1	 13	T	101	  1	  1		 15			BLN	ALPHA	 24	  0								____________	                                       00	
ZAA_TRANSFER-GJAHR	N	NUMC	  4	B0	00	80	00	00	  1	 14	T	101	  1	  1		  4			GJR	GJAHR	  8	  0								____	                                       00	
ZAA_TRANSFER-USNAM	C	CHAR	 12	B0	00	80	00	00	  1	 15	T	101	  1	  1		 12			USR		 24	  0								____________	                                       00	
ZAA_TRANSFER-CPUDT	D	DATE	 10	B0	00	80	00	08	  1	 16	T	101	  1	  1		 10					 16	  0								__________	X                                      00	
ZAA_TRANSFER-MESSAGE	C	CHAR	255	B0	00	80	00	00	  1	 17	T	101	  1	  1		255					255	  0								____________________________________________________________________________________________________________________________________	                                       00	
VIM_POSI_PUSH		CHAR	 20	80	00	88	30	00	 61	 20		  0	  0	  0		 20	P				  0	  0	103							____________________	                                                                                                                                                                        POSI	
VIM_POSITION_INFO		CHAR	 30	80	02	88	33	00	 61	 41		  0	  0	  0		 30					  0	  0								______________________________		
OK_CODE		CHAR	 20	80	10	08	00	00	255	  1	O	  0	  0	  0		 20					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
 MODULE LISTE_INITIALISIEREN.																																
 LOOP AT EXTRACT WITH CONTROL																																
  TCTRL_ZAA_TRANSFER CURSOR NEXTLINE.																																
   MODULE LISTE_SHOW_LISTE.																																
 ENDLOOP.																																
*																																
PROCESS AFTER INPUT.																																
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.																																
 MODULE LISTE_BEFORE_LOOP.																																
 LOOP AT EXTRACT.																																
   MODULE LISTE_INIT_WORKAREA.																																
   CHAIN.																																
    FIELD ZAA_TRANSFER-ZID .																																
    FIELD ZAA_TRANSFER-SERNR .																																
    FIELD ZAA_TRANSFER-BUDAT .																																
    FIELD ZAA_TRANSFER-SGTXT .																																
    FIELD ZAA_TRANSFER-SHOPSTORT .																																
    FIELD ZAA_TRANSFER-STORT .																																
    FIELD ZAA_TRANSFER-ZST .																																
    FIELD ZAA_TRANSFER-ASSETCODE .																																
    FIELD ZAA_TRANSFER-SUBNUMBER .																																
    FIELD ZAA_TRANSFER-NEWASSETCODE .																																
    FIELD ZAA_TRANSFER-NEWSUBNUMBER .																																
    FIELD ZAA_TRANSFER-BUKRS .																																
    FIELD ZAA_TRANSFER-BELNR .																																
    FIELD ZAA_TRANSFER-GJAHR .																																
    FIELD ZAA_TRANSFER-USNAM .																																
    FIELD ZAA_TRANSFER-CPUDT .																																
    FIELD ZAA_TRANSFER-MESSAGE .																																
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.																																
   ENDCHAIN.																																
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.																																
   CHAIN.																																
    FIELD ZAA_TRANSFER-ZID .																																
    FIELD ZAA_TRANSFER-SERNR .																																
    MODULE LISTE_UPDATE_LISTE.																																
   ENDCHAIN.																																
 ENDLOOP.																																
 MODULE LISTE_AFTER_LOOP.																																
