****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZRMCA_RAW_DATA_CORRECTION																																
0100																																
731																																
                40																																
%_HEADER																																
ZRMCA_RAW_DATA_CORRECTION               0100 0100      6101192 37  0  0  6133  0G E                              20150225105919																																
%_DESCRIPTION																																
ALV Screen																																
%_FIELDS																																
FRAME		CHAR	101	00	00	00	30	00	  1	  2		  0	  0	  0		  3	R				  0	  0	101			FG1				Enter new value		
FKKBIXBIT_IT_DISP-SUBPROCESS	0	CHAR	 15	30	00	04	30	00	  2	  3		  0	  0	  0		  0					  0	  0				FG1				Subprocess	                                                                                                                                                                                                                                                        X	
GV_SUBPR	C	CHAR	  4	80	00	84	00	08	  2	 19		  0	  0	  0		  0					  8	  0				FG1				____	X	
FKKVKP-VKONT	0	CHAR	 18	30	00	04	30	00	  2	 30		  0	  0	  0		  0			KTO		  0	  0				FG1				Contract Account	                                                                                                                                                                                                                                                        X	
GV_VKONT	C	CHAR	 12	80	00	84	00	08	  2	 49		  0	  0	  0		  0			KTO	ALPHA	 24	  0				FG1				____________	X	
FKKVKP-GPART	0	CHAR	 19	30	00	06	30	00	  2	 68		  0	  0	  0		  0			BPA		  0	  0				FG1				Business Partner	                                                                                                                                                                                                                                                        X	
GV_GPART	C	CHAR	 10	80	00	86	00	00	  2	 88		  0	  0	  0		  0			BPA	ALPHA	 20	  0				FG1				__________	X	
FNAME2		CHAR	101	00	00	00	30	00	  4	  2		  0	  0	  0		  3	R				  0	  0	102			FG2				Enter new value		
FKKVKP-ERDAT	0	CHAR	 17	30	00	00	30	00	  5	  3		  0	  0	  0		  0					  0	  0				FG2				Consumption Date	                                                                                                                                                                                                                                                        X	
GV_CDATE	D	DATS	 10	80	00	80	00	08	  5	 21		  0	  0	  0		  0					  8	  0			SRM_F4_DATUM	FG2				__________		
GV_OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
																																
PROCESS BEFORE OUTPUT.																																
																																
  MODULE pbo_100.																																
  MODULE set_screen.																																
																																
PROCESS AFTER INPUT.																																
																																
  MODULE exit AT EXIT-COMMAND.																																
																																
  CHAIN.																																
    FIELD gv_subpr.																																
    MODULE check_subprocess ON CHAIN-REQUEST.																																
																																
    FIELD gv_vkont.																																
    MODULE check_cont_acc ON CHAIN-REQUEST.																																
																																
    FIELD gv_gpart.																																
    MODULE check_bus_partner ON CHAIN-REQUEST.																																
  ENDCHAIN.																																
																																
  MODULE pai_100.																																
