****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZRMCA_BAD_DEBTS																																
0100																																
731																																
                40																																
%_HEADER																																
ZRMCA_BAD_DEBTS                         0100 0100      0  0192 37  0  0 27120  0G E                              20150818112146																																
%_DESCRIPTION																																
ALV Screen																																
%_FIELDS																																
GV_OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________	                                       00	
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
  MODULE pbo_100.																																
																																
PROCESS AFTER INPUT.																																
  MODULE pai_100.																																
