****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZSD_SERIAL																																
0100																																
700																																
                40																																
%_HEADER																																
ZSD_SERIAL                              0100 0100      0  0192 37  0  0 27120  0G E                              20150609094649																																
%_DESCRIPTION																																
ALV screen																																
%_FIELDS																																
GV_OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
  MODULE pbo_100.																																
																																
PROCESS AFTER INPUT.																																
  MODULE pai_100.																																
