****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZZBILLHEADER																																
0001																																
700																																
                40																																
%_HEADER																																
ZZBILLHEADER                            0001 0001      2 11192 37  0  0 27120  0G T                              20140508114448																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SNO		CHAR	 10	00	00	00	30	00	  2	  3		  0	  0	  0		  0	P				  0	  0	101							Sipair# No	                                                                                                                                                                        VA01	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0001.																																
*																																
PROCESS AFTER INPUT.																																
* MODULE USER_COMMAND_0001.																																
