****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZAA_TRANSFER_MAINTAIN																																
9001																																
700																																
                40																																
%_HEADER																																
ZAA_TRANSFER_MAINTAIN                   9001 9001      0  0192 37  0  0 27120  0G E                              20151214142934																																
%_DESCRIPTION																																
edit table screen																																
%_FIELDS																																
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
 MODULE STATUS_9001.																																
*																																
PROCESS AFTER INPUT.																																
 MODULE USER_COMMAND_9001.																																
